# Generated by Django 5.1.15 on 2026-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_accountgroup_created_at_accountgroup_created_by_and_more'),
    ]

    operations = [
        # Postgres has no direct integer->uuid cast, so a plain AlterField (which Django
        # expresses as "ALTER COLUMN ... TYPE uuid USING reference_id::uuid") fails even though
        # the table is empty (confirmed via JournalEntry.objects.count() == 0) and there's
        # nothing to actually cast. Dropping and re-adding the column sidesteps that entirely.
        migrations.RemoveField(
            model_name='journalentry',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
