# Generated by Django 5.1.15 on 2026-08-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseinvoice_purchaseinvoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='gst_type',
            field=models.CharField(choices=[('EXCLUSIVE', 'Exclusive'), ('INCLUSIVE', 'Inclusive'), ('NO_GST', 'No GST')], default='EXCLUSIVE', max_length=10),
        ),
    ]
