# Generated by Django 5.1.15 on 2026-08-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchaseinvoice_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='company_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_interstate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='cess_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='igst_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='sgst_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
