# Generated by Django 5.1.15 on 2026-08-18 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_journalentry_reference_id'),
        ('purchasing', '0005_purchaseinvoice_supplier_vat_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('last_number', models.BigIntegerField(default=1000)),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='financial.chartofaccount'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
