# Generated by Django 5.1.15 on 2026-09-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_branch_options_branch_city_branch_country_and_more'),
        ('purchasing', '0006_suppliercodesequence_supplier_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.branch'),
        ),
    ]
