# Generated by Django 5.2.16 on 2026-07-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='importbatch',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='importerrorlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='importerrorlog',
            name='updated_by',
        ),
    ]
