# Generated by Django 5.1.15 on 2026-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_barcode_alter_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='column_headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='processed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Validation'), ('PROCESSING', 'Importing In Background'), ('VALIDATED', 'Validated Ready'), ('SUCCESS', 'Import Successful'), ('PARTIAL', 'Partial Import'), ('FAILED', 'Import Failed'), ('ARCHIVED', 'Archived Batch'), ('DELETED', 'Deleted Batch')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
