# Generated by Django 5.1.15 on 2026-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_color_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
