# Generated by Django 5.1.15 on 2026-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_patientcodesequence_customer_age_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.CharField(default='Standard Booking', max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Booked', max_length=20),
        ),
    ]
