# Generated by Django 5.1.15 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_appointment_priority_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='test_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
