# Generated by Django 5.1.15 on 2026-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fulfillment_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
