# Generated by Django 5.2.16 on 2026-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_invoice_fulfillment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNoSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('last_number', models.BigIntegerField(default=1000)),
            ],
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='test_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
