# Generated by Django 5.1.15 on 2026-09-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_invoice_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='power',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
