# Generated by Django 5.1.15 on 2026-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_invoiceitem_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
